---
- name: Install Zabbix Server
  hosts: monitoring
  become: yes
  tasks:
    - name: Install gpg and curl
      apt:
        name: [gpg, curl]
        state: present
        update_cache: yes

    - name: Download Zabbix GPG key
      shell: "curl -s https://repo.zabbix.com/zabbix-official-repo.key | gpg --dearmor --yes -o /usr/share/keyrings/zabbix-keyring.gpg"

    - name: Add Zabbix repository (for Ubuntu 22.04 Jammy)
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/zabbix-keyring.gpg] https://repo.zabbix.com/zabbix/6.0/ubuntu jammy main"
        state: present

    - name: Install Zabbix components
      apt:
        name:
          - zabbix-server-mysql
          - zabbix-frontend-php
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
          - mysql-server
        state: present
        update_cache: yes

    - name: Ensure MySQL is running
      service:
        name: mysql
        state: started
        enabled: yes

- name: Install Zabbix Agent on Web Server
  hosts: web_servers
  become: yes
  tasks:
    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present
        update_cache: yes

    - name: Configure Zabbix Agent (point to server)
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=192.168.10.33' # Внутренний IP Zabbix-сервера

    - name: Restart Zabbix Agent
      service:
        name: zabbix-agent
        state: restarted
        enabled: yes
